name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Specific Gradle 8.10
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.10' # Принудительно ставим стабильную 8-ю версию
          cache-disabled: true

      - name: Build Mod with Gradle 8
        run: gradle build --no-daemon
